[package]
name = "riui"
version = "0.1.0"
authors = ["mswift42 <martin.haesler@gmail.com>"]
edition = "2018"

[dependencies]
roxmltree = "0.6.0"
serde-xml-rs = "0.3.1"
serde = { version = "1.0.91", features = ["derive"] }
